s="amity"
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.islower())          
print(s.isupper())
print(s.count('a'))     
print(s.replace('m','M'))
print(s.find('i'))
print(s.index('t'))
print(s.split('m'))
print(s.startswith('a'))
print(s.endswith('y'))
print(s.swapcase())
print(s.center(11,'*'))
print(len(s))
s1="heelo"
s2="world"
s3=s1+s2
print(s3)